### ISSUE TITLE
Game does not start after being patched

### ISSUE THREAD

**Issue by Iltotore** [Brian0255/Pokemon-Black-and-White-Intro-Speedup#1]
Patch version: 1.2.1

After patching this rom (which works normally without patching) and launching it, it simply does not work and shows a white screen.

**Comment by Brian0255** [comment]
Please do not share where you downloaded ROMs from as that is illegal. As to why a ROM would not work with the intro patch, that can happen if the ROM is not clean or it's not an English ROM. I cannot help you find a correct one, you are unfortunately on your own for that.
